import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
  Row,
  Column,
} from "@react-email/components";
import type { StartupReport } from "@/lib/types";

interface ReportEmailProps {
  report: StartupReport;
  reportUrl: string;
}

export function ReportEmail({ report, reportUrl }: ReportEmailProps) {
  const businessName = report.intake.businessName || `${report.intake.userName}'s Plan`;
  const score = report.viability.overallScore;
  const scoreColor = score >= 70 ? "#059669" : score >= 50 ? "#d97706" : "#dc2626";

  return (
    <Html>
      <Head />
      <Preview>
        {`Your LaunchWise report for ${businessName} is ready — viability score: ${score}/100`}
      </Preview>
      <Body style={body}>
        {/* Header */}
        <Section style={header}>
          <Text style={brandName}>LaunchWise</Text>
          <Text style={brandTagline}>Your startup navigator</Text>
        </Section>

        <Container style={container}>
          {/* Intro */}
          <Heading style={h1}>Your Launch Report is Ready</Heading>
          <Text style={intro}>
            Hi {report.intake.userName}, here's a summary of your startup analysis for{" "}
            <strong>{businessName}</strong> in {report.intake.city}, {report.intake.state}.
          </Text>

          {/* Viability score card */}
          <Section style={scoreCard}>
            <Text style={scoreLabel}>VIABILITY SCORE</Text>
            <Text style={{ ...scoreValue, color: scoreColor }}>{score}</Text>
            <Text style={scoreOutOf}>/100</Text>
            <Text style={scoreVerdict}>{report.viability.verdict}</Text>
          </Section>

          <Hr style={divider} />

          {/* Key metrics */}
          <Heading style={h2}>Key Metrics at a Glance</Heading>
          <Row>
            <Column style={metricBox}>
              <Text style={metricLabel}>Market Demand</Text>
              <Text style={metricValue}>{capitalize(report.ideaAnalysis.marketDemand)}</Text>
            </Column>
            <Column style={metricBox}>
              <Text style={metricLabel}>Competition</Text>
              <Text style={metricValue}>{capitalize(report.ideaAnalysis.competitionLevel)}</Text>
            </Column>
            <Column style={metricBox}>
              <Text style={metricLabel}>Profit Potential</Text>
              <Text style={metricValue}>{capitalize(report.ideaAnalysis.profitPotential)}</Text>
            </Column>
          </Row>

          <Hr style={divider} />

          {/* Top strengths */}
          {report.viability.topStrengths.length > 0 && (
            <>
              <Heading style={h2}>Top Strengths</Heading>
              {report.viability.topStrengths.slice(0, 3).map((strength, i) => (
                <Text key={i} style={listItem}>
                  <span style={bullet}>✓</span> {strength}
                </Text>
              ))}
            </>
          )}

          {/* Key risks */}
          {report.viability.topRisks.length > 0 && (
            <>
              <Heading style={h2}>Key Risks to Watch</Heading>
              {report.viability.topRisks.slice(0, 3).map((risk, i) => (
                <Text key={i} style={listItem}>
                  <span style={riskBullet}>!</span> {risk}
                </Text>
              ))}
            </>
          )}

          {/* Critical first steps */}
          {report.viability.criticalFirstSteps.length > 0 && (
            <>
              <Hr style={divider} />
              <Heading style={h2}>Critical First Steps</Heading>
              {report.viability.criticalFirstSteps.slice(0, 3).map((step, i) => (
                <Text key={i} style={listItem}>
                  <span style={stepNumber}>{i + 1}.</span> {step}
                </Text>
              ))}
            </>
          )}

          <Hr style={divider} />

          {/* CTA */}
          <Section style={ctaSection}>
            <Text style={ctaText}>
              Your full report includes a 9-section deep dive: roadmap, local requirements,
              competitor analysis, branding feedback, 90-day plan, and more.
            </Text>
            <Button style={ctaButton} href={reportUrl}>
              View Full Report
            </Button>
          </Section>

          <Hr style={divider} />

          {/* Footer */}
          <Text style={footer}>
            This report was generated by LaunchWise · launch-pilot.com
          </Text>
          <Text style={footerSub}>
            AI-generated planning tool — not a substitute for legal, tax, or professional advice.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const body: React.CSSProperties = {
  backgroundColor: "#faf9f7",
  fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  margin: 0,
  padding: 0,
};

const header: React.CSSProperties = {
  backgroundColor: "#4f46e5",
  padding: "24px 32px",
  textAlign: "center",
};

const brandName: React.CSSProperties = {
  color: "#ffffff",
  fontSize: "24px",
  fontWeight: "700",
  margin: "0 0 4px",
  letterSpacing: "-0.5px",
};

const brandTagline: React.CSSProperties = {
  color: "#c7d2fe",
  fontSize: "13px",
  margin: 0,
};

const container: React.CSSProperties = {
  backgroundColor: "#ffffff",
  maxWidth: "560px",
  margin: "0 auto",
  padding: "32px 40px",
  borderRadius: "0 0 12px 12px",
  boxShadow: "0 4px 24px rgba(0,0,0,0.06)",
};

const h1: React.CSSProperties = {
  color: "#1e1b4b",
  fontSize: "22px",
  fontWeight: "700",
  margin: "0 0 12px",
  letterSpacing: "-0.3px",
};

const h2: React.CSSProperties = {
  color: "#1e1b4b",
  fontSize: "15px",
  fontWeight: "600",
  margin: "16px 0 8px",
  textTransform: "uppercase",
  letterSpacing: "0.5px",
};

const intro: React.CSSProperties = {
  color: "#27272a",
  fontSize: "15px",
  lineHeight: "1.6",
  margin: "0 0 24px",
};

const scoreCard: React.CSSProperties = {
  backgroundColor: "#eef2ff",
  borderRadius: "12px",
  padding: "24px",
  textAlign: "center",
  margin: "0 0 8px",
};

const scoreLabel: React.CSSProperties = {
  color: "#6366f1",
  fontSize: "11px",
  fontWeight: "600",
  letterSpacing: "1.5px",
  textTransform: "uppercase",
  margin: "0 0 4px",
};

const scoreValue: React.CSSProperties = {
  fontSize: "56px",
  fontWeight: "800",
  lineHeight: "1",
  margin: "0",
  display: "inline",
};

const scoreOutOf: React.CSSProperties = {
  color: "#71717a",
  fontSize: "20px",
  fontWeight: "400",
  margin: "0 0 8px",
};

const scoreVerdict: React.CSSProperties = {
  color: "#27272a",
  fontSize: "14px",
  lineHeight: "1.5",
  margin: "12px 0 0",
  fontStyle: "italic",
};

const divider: React.CSSProperties = {
  borderColor: "#e7e5e0",
  margin: "24px 0",
};

const metricBox: React.CSSProperties = {
  backgroundColor: "#faf9f7",
  borderRadius: "8px",
  padding: "12px 8px",
  textAlign: "center",
  width: "33%",
};

const metricLabel: React.CSSProperties = {
  color: "#71717a",
  fontSize: "11px",
  fontWeight: "500",
  textTransform: "uppercase",
  letterSpacing: "0.5px",
  margin: "0 0 4px",
};

const metricValue: React.CSSProperties = {
  color: "#27272a",
  fontSize: "15px",
  fontWeight: "600",
  margin: 0,
};

const listItem: React.CSSProperties = {
  color: "#27272a",
  fontSize: "14px",
  lineHeight: "1.6",
  margin: "0 0 6px",
  paddingLeft: "4px",
};

const bullet: React.CSSProperties = {
  color: "#059669",
  fontWeight: "700",
  marginRight: "6px",
};

const riskBullet: React.CSSProperties = {
  color: "#d97706",
  fontWeight: "700",
  marginRight: "6px",
};

const stepNumber: React.CSSProperties = {
  color: "#6366f1",
  fontWeight: "700",
  marginRight: "6px",
};

const ctaSection: React.CSSProperties = {
  textAlign: "center",
  padding: "8px 0",
};

const ctaText: React.CSSProperties = {
  color: "#71717a",
  fontSize: "14px",
  lineHeight: "1.6",
  margin: "0 0 20px",
};

const ctaButton: React.CSSProperties = {
  backgroundColor: "#4f46e5",
  borderRadius: "10px",
  color: "#ffffff",
  fontSize: "15px",
  fontWeight: "600",
  padding: "13px 32px",
  textDecoration: "none",
  display: "inline-block",
};

const footer: React.CSSProperties = {
  color: "#71717a",
  fontSize: "12px",
  textAlign: "center",
  margin: "0 0 4px",
};

const footerSub: React.CSSProperties = {
  color: "#a1a1aa",
  fontSize: "11px",
  textAlign: "center",
  margin: 0,
};
