export const metadata = {
  title: "Terms of Service — LaunchPilot",
};

export default function TermsPage() {
  return (
    <section className="py-16 bg-white min-h-screen">
      <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-primary-900 mb-2">Terms of Service</h1>
        <p className="text-text-muted text-sm mb-8">Last updated: March 20, 2026</p>

        <div className="prose prose-sm max-w-none space-y-6 text-text">
          <div>
            <h2 className="text-lg font-bold text-primary-900 mb-2">Acceptance of Terms</h2>
            <p className="text-sm leading-relaxed text-text-muted">
              By using LaunchPilot (&quot;the Service&quot;), you agree to these Terms of Service. If you do not agree, please do not use the Service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-primary-900 mb-2">What LaunchPilot Is</h2>
            <p className="text-sm leading-relaxed text-text-muted">
              LaunchPilot is an AI-powered planning tool that generates personalized startup reports based on your inputs. It provides general guidance to help you plan your business launch.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-primary-900 mb-2">What LaunchPilot Is Not</h2>
            <p className="text-sm leading-relaxed text-text-muted">
              LaunchPilot is not a substitute for professional legal, tax, financial, or business advice. The information provided in reports is AI-generated and may contain inaccuracies. You should verify all licensing requirements, legal obligations, and business regulations with the appropriate local, state, and federal agencies before acting on any recommendations.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-primary-900 mb-2">Your Responsibilities</h2>
            <p className="text-sm leading-relaxed text-text-muted">
              You are responsible for providing accurate information in the questionnaire. You are responsible for independently verifying all recommendations, requirements, and information in your report before making business decisions. You acknowledge that AI-generated content may not always be accurate or up-to-date.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-primary-900 mb-2">Intellectual Property</h2>
            <p className="text-sm leading-relaxed text-text-muted">
              Your business ideas, names, and concepts remain your intellectual property. Reports generated by LaunchPilot are provided for your personal use. The LaunchPilot brand, design, and underlying technology are the property of LaunchPilot.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-primary-900 mb-2">Limitation of Liability</h2>
            <p className="text-sm leading-relaxed text-text-muted">
              LaunchPilot is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to business decisions made based on report recommendations. Our total liability is limited to the amount you paid for the Service (if any).
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-primary-900 mb-2">Changes to Terms</h2>
            <p className="text-sm leading-relaxed text-text-muted">
              We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold text-primary-900 mb-2">Contact</h2>
            <p className="text-sm leading-relaxed text-text-muted">
              Questions about these terms? Contact us at legal@launch-pilot.com.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
